name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Checkout repo (including submodules)
      uses: actions/checkout@v4
      with:
        submodules: recursive
        persist-credentials: true
        fetch-depth: 0

    - name: Defensive sync
      run: |
        git submodule sync --recursive
        git submodule update --init --recursive
        git submodule status

    - name: Compile libsais
      run:
        cd libsais; cmake .; make; cd ..  
        
    - name: run
      run: ./ptest.sh web cnr80k
    # - name: configure
    #   run: ./configure
    # - name: make
    #   run: make
    # - name: make check
    #   run: make check
    # - name: make distcheck
    #   run: make distcheck
