name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Compile libsais
      run:
        cd libsais; cmake .; make; cd ..

    - name: make
      run: make  
        
    - name: run
      run: ./ptest.sh web cnr80k

    - name: check
      run: ./k2sparse.x web/cnr80k.k2 -d -o sparsek2.txt;   
           ./k2sparse.x web/cnr80k.ck2 -d -I web/cnr80k.ck2.p -o sparseck2.txt;
           ./matrixcmp.x sparsek2.txt sparseck2.txt 

    - name: test add diag
      run: |
          ./sparsetr.py sparsek2.txt -d -o sparsek2.1.ok  # traspose the original matrix
          echo "Unary operations on web/cnr80k.k2"
          ./k2unary.x web/cnr80k.k2  -o sparsek2             # creates sparsek2.tr.txt sparsek2.tr1.txt
          echo "Compare matrices"
          ./matrixcmp.x sparsek2.1.txt sparsek2.1.ok

    - name: big traspose test 
      run: ./trdtest.sh sparsek2.txt
  

    # - name: configure
    #   run: ./configure
    # - name: make
    #   run: make
    # - name: make check
    #   run: make check
    # - name: make distcheck
    #   run: make distcheck
